name: user_web
port: 8888
user_srv:
  name: user_srv
jwt:
  key: "sadava12whbcb128^^*%%sjacvwhassc"
redis:
  host: 172.26.25.139
  port: 30079
  password: admin123
  expire: 300
consul:
  host: "172.26.25.139"
  port: 30500