name: order_web
host: 10.8.117.74
port: 8892
tags:
  - order_web
  - alan
goods_srv:
  name: goods_srv
order_srv:
  name: order_srv
inventory_srv:
  name: inventory_srv
jwt:
  key: "sadava12whbcb128^^*%%sjacvwhassc"
consul:
  host: "172.26.25.139"
  port: 30500